### ISSUE TITLE
Format of database entries

### ISSUE THREAD

**Issue by billyfung** [billyfung/tellmeabout.coffee#11]
Should have a standard for what the entries into the db will be in, like for size, should we do value + unit, or convert into one standard unit for all?

**Comment by jinpark** [comment]
I'm good with either way, what do you think is the best way?

**Comment by billyfung** [comment]
Easiest to just make it a string for now, then display size + units along with price, then also have another column for price/g or price/oz

**Comment by jinpark** [comment]
ok can you make a PR for that?

**Comment by billyfung** [comment]
yessir

**Comment by jinpark** [comment]
Make a pr and when that pr gets merged, we can close the issue :)
