### ISSUE TITLE
What do we want to track per coffee?

### ISSUE THREAD

**Issue by jinpark** [billyfung/tellmeabout.coffee#2]
- Name
- Roaster
- Date Added
- Date Removed
- Description
  ???

**Comment by billyfung** [comment]
- Tasting notes
- Location

**Comment by billyfung** [comment]
- Size of bag
- product url

**Comment by jinpark** [comment]
Do we need units if we're doing size of bag?

**Comment by jinpark** [comment]
wejust decided to make size a string for now. and im going to close this for now
