### ISSUE TITLE
Add lazyloading for images

### ISSUE THREAD

**Issue by jinpark** [billyfung/tellmeabout.coffee#42]
Should save bandwidth (not that we pay for it)

**Comment by jinpark** [comment]
https://github.com/jinpark/tellmeabout.coffee/pull/41

**Comment by jinpark** [comment]
D o N e

**Comment by billyfung** [comment]
When testing locally, it seems like if I filter first the images don't load. Works fine on the deployed version though

**Comment by billyfung** [comment]
fixed
