### ISSUE TITLE
Query and update db

### ISSUE THREAD

**Issue by billyfung** [billyfung/tellmeabout.coffee#6]
Not sure what is the best way to query and update the db to show that the coffee is no longer in stock. Grab the product url and then see if it works?

**Comment by jinpark** [comment]
Not sure, some brands show a `sold out` notice, others just remove it from the page.

If its removed, I think easiest way is when you run the scraper, compare the coffees you get with whats already in the DB for that roaster and say whatever is not updated or new, is OOS

**Comment by jinpark** [comment]
this is doneee
