### ISSUE TITLE
Fix scrapers

### ISSUE THREAD

**Issue by jinpark** [billyfung/tellmeabout.coffee#91]
Websites have changed, our scrapers dont work

Billy takes these four
- [x] bluebottle.py
- [x] fortyninth.py
- [x] heart.py
- [x] intelli.py

Jin takes these three
- [x] matchstick.py #92 
- [x] stumptown.py #93
- [x] victrola.py #94

**Comment by billyfung** [comment]
victrola scraper seems to run fine

Edit: nvm it doesnt

**Comment by billyfung** [comment]
https://www.intelligentsiacoffee.com/coffee might need selenium since it loads the coffee from scrolling

**Comment by jinpark** [comment]
talked to billy and we figured out the ajax calls that intelligensia was making

**Comment by billyfung** [comment]
ok seems all done
